# -*- coding: utf-8 -*-
"""Generate the five non-scoliosis education hubs and their articles.

Each hub lives in its own directory under site/ and owns one index page plus
its articles. Content comes from topics/*.json so the prose can be edited
without touching the template, exactly as the scoliosis library works.

The scoliosis hub is generated by build_articles.py instead. It carries a
much deeper tree, so it has its own richer landing page and is left alone.
"""
import io, json, math, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.normpath(os.path.join(HERE, "..", "site"))
TOPICS = os.path.join(HERE, "topics")
BASE = "https://ronimassoud.github.io/rayhab-movement-clinic"

ORDER = ["exercise", "sport", "posture", "mobility", "injury"]

# Where each hub points when it sends a reader somewhere else on the site.
# Keyed by directory, so a new topic file fails loudly rather than silently
# producing a hub with no onward links.
CROSS = {
    "exercise": [
        ("../services/frc-joint-training.html", "Service", "FRC &amp; joint training",
         "Where the loading principles on this page turn into a programme."),
        ("../scoliosis/lifting-with-scoliosis.html", "Scoliosis", "Lifting with scoliosis",
         "The same loading logic, applied to a spine with a known curve."),
        ("../mobility/", "Hub", "Mobility &amp; joint health",
         "Range you can control, and why strength at end range is the other half of loading."),
    ],
    "sport": [
        ("../services/sports-rehabilitation.html", "Service", "Sports rehabilitation",
         "Assessment, criteria and a graded return, run as a programme."),
        ("../scoliosis/return-to-sport.html", "Scoliosis", "Returning to sport with a curve",
         "What changes, and what does not, when the athlete has scoliosis."),
        ("../injury/how-long-does-rehab-take.html", "Injury rehabilitation", "How long does rehabilitation take?",
         "Realistic timeframes, including for a return to high-demand sport."),
    ],
    "posture": [
        ("../scoliosis/what-scoliosis-actually-is.html", "Scoliosis", "What scoliosis actually is",
         "A structural, three-dimensional condition, which is not a posture habit."),
        ("../scoliosis/", "Hub", "Understanding scoliosis",
         "The deepest section on the site, for curves rather than posture."),
        ("../mobility/passive-versus-active-range.html", "Mobility", "Range you can control",
         "Why capacity in a position matters more than the position itself."),
    ],
    "mobility": [
        ("../services/frc-joint-training.html", "Service", "FRC &amp; joint training",
         "Controlled articular rotations and end-range work, programmed and progressed."),
        ("../exercise/progressive-overload-without-flare-ups.html", "Exercise &amp; loading", "Progressive overload",
         "How load is added without provoking the thing you are trying to build."),
        ("../injury/hip-and-groin-pain.html", "Injury rehabilitation", "Hip and groin pain",
         "What hip shape findings mean, and why loading beats releasing."),
    ],
    "injury": [
        ("../services/physiotherapy.html", "Service", "Physiotherapy",
         "Assessment, diagnosis and an active plan you leave with."),
        ("../exercise/stop-training-advice.html", "Exercise &amp; loading", "When stopping is the wrong advice",
         "Why rest resolves the flare-up and leaves the cause in place."),
        ("../sport/return-criteria-not-calendar.html", "Sport", "Return criteria, not a calendar",
         "What has to be true before you go back to something demanding."),
    ],
}

NAV = '''<nav class="site-nav" aria-label="Primary">
  <a href="../" aria-label="Rayhab Movement Clinic, home"><span class="wordmark"></span></a>
  <button class="nav-toggle" type="button" aria-expanded="false" aria-controls="navgroup"><i></i><span class="vh">Menu</span></button>
  <div class="navgroup" id="navgroup">
    <a href="../">Home</a>
    <a href="../scoliosis/">Scoliosis</a>
    <a href="../services/">Services</a>
    <a href="../about.html">About</a>
    <a href="../results.html">Results</a>
    <a href="../education.html" aria-current="page">Education</a>
    <a href="../contact.html">Contact</a>
  </div>
  <div class="nav-right">
    <span class="nav-meta">Beirut · Online</span>
    <a class="btn btn-spring btn-sm" href="../book.html">Book an assessment</a>
  </div>
</nav>'''

FOOTER = '''<footer class="site-footer">
  <div>
    <span class="wordmark"></span>
    <p class="foot-tag">MOVEMENT CLINIC</p>
    <div class="socials">
      <a href="https://instagram.com/" aria-label="Instagram"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#B4C7B8" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="3.5" y="3.5" width="17" height="17" rx="5"></rect><circle cx="12" cy="12" r="3.9"></circle><circle cx="17.1" cy="6.9" r="1" fill="#B4C7B8" stroke="none"></circle></svg></a>
      <a href="https://tiktok.com/" aria-label="TikTok"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#B4C7B8" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M13.4 3.5v10.9a3.4 3.4 0 11-3.4-3.4"></path><path d="M13.4 3.5c.3 2.4 2 4.1 4.4 4.3"></path></svg></a>
      <a href="https://facebook.com/" aria-label="Facebook"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#B4C7B8" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M14.8 7.4h2.1"></path><path d="M14.8 20.5V8.9a2.4 2.4 0 012.4-2.4h.6"></path><path d="M11.6 12.3h4.9"></path></svg></a>
    </div>
  </div>
  <div class="footcols">
    <div class="footcol">
      <h2>Scoliosis</h2>
      <a href="../scoliosis/">Understanding scoliosis</a>
      <a href="../education.html">Education hub</a>
      <a href="../results.html">Case studies</a>
    </div>
    <div class="footcol">
      <h2>Services</h2>
      <a href="../services/scoliosis-rehabilitation.html">Scoliosis rehabilitation</a>
      <a href="../services/sports-rehabilitation.html">Sports rehabilitation</a>
      <a href="../services/frc-joint-training.html">FRC &amp; joint training</a>
      <a href="../services/physiotherapy.html">Physiotherapy</a>
    </div>
    <div class="footcol">
      <h2>Clinic</h2>
      <a href="../about.html">About Rayan</a>
      <a href="../contact.html">Contact</a>
      <a href="../book.html">Online consultations</a>
    </div>
  </div>
</footer>

<div class="m-bookbar">
  <p class="m-bookbar-1">Ready to turn this into your plan?</p>
  <a class="btn btn-spring" href="../book.html">Book</a>
</div>'''

HEAD = '''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<link rel="canonical" href="{canon}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,400;12..96,500;12..96,600;12..96,700&family=Public+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../assets/css/rayhab.css">
<link rel="stylesheet" href="../assets/css/mobile.css">
<link rel="stylesheet" href="../assets/css/booking.css">
<link rel="icon" href="../assets/img/rayhab-logo.png">
</head>
<body>
<a class="skip" href="#main">Skip to content</a>
<div class="frame">

'''

TAIL = '''
</div>
<script src="../assets/js/ui.js"></script>
<script src="../assets/js/booking.js"></script>
<script src="../assets/js/modal.js"></script>
</body>
</html>
'''

CTA = '''  <section class="cta-band" style="padding:56px var(--pad-x)">
    <div>
      <h2 class="h2-sm cta-h2">{h}</h2>
      <p class="body-m cta-lede">{p}</p>
    </div>
    <div class="btns">
      <a class="btn btn-forest" href="../book.html">Book an assessment</a>
      <a class="btn btn-ghost-ink" href="{href}">{label}</a>
    </div>
  </section>
'''


def wrap_arrows(html):
    """Wrap trailing navigational arrows so they can animate on hover.
    The leading space is what separates a navigational arrow from a data
    one such as "29 -> 20", so data arrows are left alone."""
    return html.replace(u" →</", u' <span class="arw" aria-hidden="true">→</span></')


def esc(t):
    return t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def inline(t):
    """Allow **bold** in the source prose."""
    return re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", esc(t))


def render_blocks(blocks):
    out = []
    for b in blocks:
        k = b["k"]
        if k == "h":
            out.append('<h2 id="%s">%s</h2>' % (b["id"], esc(b["t"])))
        elif k == "h3":
            out.append("<h3>%s</h3>" % esc(b["t"]))
        elif k == "p":
            out.append("<p>%s</p>" % inline(b["t"]))
        elif k in ("ul", "ol"):
            items = "".join("<li>%s</li>" % inline(i) for i in b["items"])
            out.append("<%s>%s</%s>" % (k, items, k))
        elif k == "uncertain":
            out.append('<div class="uncertain"><h2>What is not settled</h2><p>%s</p></div>'
                       % inline(b["t"]))
    return "\n      ".join(out)


def reading_time(a):
    """Derive the reading time from the text itself rather than trusting a
    hand-written estimate, which is what drifted on the scoliosis set."""
    words = []
    for k in a["key"]:
        words += k.split()
    for b in a["blocks"]:
        if "t" in b:
            words += b["t"].split()
        for i in b.get("items", []):
            words += i.split()
    return "%d min read" % max(2, math.ceil(len(words) / 200.0))


def render_article(a, topic, lookup):
    heads = [b for b in a["blocks"] if b["k"] == "h"]
    toc = "".join('<li><a href="#%s">%s</a></li>' % (h["id"], esc(h["t"])) for h in heads)
    keys = "".join("<li>%s</li>" % inline(k) for k in a["key"])

    related = ""
    for s in a.get("related", [])[:3]:
        r = lookup[s]
        related += ('<a class="morecard" href="%s.html">'
                    '<p class="art-kicker">%s</p>'
                    '<h3 class="art-t">%s</h3>'
                    '<p class="art-d">%s</p></a>'
                    % (s, esc(topic["short"]), esc(r["title"]), esc(r["blurb"])))

    body = HEAD.format(title=esc(a["title"]) + ", Rayhab Movement Clinic",
                       desc=esc(a["desc"]),
                       canon="%s/%s/%s.html" % (BASE, topic["dir"], a["slug"]))
    body += NAV + "\n\n<main id=\"main\">\n\n"
    body += '''  <article>
  <header class="art-hero">
    <p class="crumbs crumbs-dark"><a href="../">Home</a> <span aria-hidden="true">/</span> <a href="../education.html">Education</a> <span aria-hidden="true">/</span> <a href="./">%s</a></p>
    <p class="art-eyebrow" style="margin-top:18px">%s</p>
    <h1 class="art-h1">%s</h1>
    <p class="art-stand">%s</p>
    <div class="art-metarow">
      <div><span class="art-metak">Reading time</span><span class="art-metav">%s</span></div>
      <div><span class="art-metak">Written by</span><span class="art-metav">%s</span></div>
      <div><span class="art-metak">Status</span><span class="art-metav">Awaiting clinical review</span></div>
    </div>
  </header>

  <div class="artwrap">
    <div class="prose">
      <div class="keybox">
        <h2>In short</h2>
        <ul>%s</ul>
      </div>
      %s
    </div>

    <aside class="art-side">
      <nav class="toc" aria-label="On this page">
        <h2>On this page</h2>
        <ol>%s</ol>
      </nav>
      <div class="reviewbox">
        <p class="review-k">Clinical reviewer</p>
        <p class="review-n">Rayan Halimeh</p>
        <p class="review-v">Physiotherapist, Certified Schroth Practitioner, Certified Mobility Specialist (FRCms), ACE Medical Exercise Specialist.</p>
        <span class="review-pending">Awaiting clinical review</span>
      </div>
      <div class="reviewbox" style="background:var(--bone)">
        <p class="review-k">General information</p>
        <p class="review-v">%s</p>
      </div>
    </aside>
  </div>
''' % (esc(topic["name"]), esc(topic["short"]), esc(a["title"]), esc(a["stand"]),
       esc(reading_time(a)), esc(topic["byline"]), keys, render_blocks(a["blocks"]),
       toc, esc(topic["note"]))

    if related:
        body += ('\n  <section class="art-more">\n    <div class="sechead">\n      <div>'
                 '<p class="eyebrow" style="margin-bottom:14px">Keep reading</p>'
                 '<h2 class="h2-sm" style="color:var(--forest-900)">Related in this hub</h2>'
                 '</div>\n      <a class="textlink" href="./">All %s →</a>\n    </div>'
                 '\n    <div class="morelist">%s</div>\n  </section>\n'
                 % (esc(topic["name"].lower()), related))

    body += "\n" + CTA.format(h=esc(a.get("cta_h", topic["cta_h"])),
                              p=esc(a.get("cta_p", topic["cta_p"])),
                              href="./", label="Back to " + esc(topic["name"].lower()))
    body += "\n</article>\n\n</main>\n\n" + FOOTER + TAIL
    return body


def render_hub(topic, arts):
    rows = ""
    for i, a in enumerate(arts, 1):
        rows += ('<a class="pidx" href="%s.html">'
                 '<span class="pidx-n">%02d</span>'
                 '<span><span class="pidx-t" style="display:block">%s</span>'
                 '<span class="pidx-d" style="display:block">%s</span></span>'
                 '<span class="pidx-go">Read →</span></a>'
                 % (a["slug"], i, esc(a["title"]), esc(a["blurb"])))

    cross = ""
    for href, kicker, title, blurb in CROSS[topic["dir"]]:
        cross += ('<a class="morecard" href="%s">'
                  '<p class="art-kicker">%s</p>'
                  '<h3 class="art-t">%s</h3>'
                  '<p class="art-d">%s</p></a>' % (href, kicker, title, blurb))

    body = HEAD.format(title=esc(topic["name"]) + ", Rayhab Movement Clinic",
                       desc=esc(topic["desc"]),
                       canon="%s/%s/" % (BASE, topic["dir"]))
    body += NAV + "\n\n<main id=\"main\">\n\n"
    body += '''  <section class="art-hero">
    <p class="crumbs crumbs-dark"><a href="../">Home</a> <span aria-hidden="true">/</span> <a href="../education.html">Education</a></p>
    <p class="art-eyebrow" style="margin-top:18px">Education hub</p>
    <h1 class="art-h1">%s</h1>
    <p class="art-stand">%s</p>
  </section>

  <section class="band" style="background:var(--paper)">
    <div class="sechead">
      <div>
        <p class="eyebrow" style="margin-bottom:14px">%d articles</p>
        <h2 class="h2-sm" style="color:var(--forest-900)">Read in order, or jump in</h2>
      </div>
      <a class="textlink" href="../education.html">All topic areas →</a>
    </div>
    <p class="body-m" style="max-width:720px;margin-bottom:30px">%s</p>
    <div class="pidx-list">%s</div>
    <p class="disclaimer" style="margin-top:26px">Every article on this page is written for patients and families, not clinicians, and carries a named clinical reviewer. Where the evidence is genuinely unsettled, the article says so rather than picking a side. General information cannot tell you what is happening in your own case.</p>
  </section>

  <section class="art-more" style="background:var(--bone)">
    <div class="sechead">
      <div>
        <p class="eyebrow" style="margin-bottom:14px">Related elsewhere</p>
        <h2 class="h2-sm" style="color:var(--forest-900)">Where this connects</h2>
      </div>
      <a class="textlink" href="../services/">All services →</a>
    </div>
    <div class="morelist">%s</div>
  </section>
''' % (esc(topic["name"]), esc(topic["stand"]), len(arts), esc(topic["lede"]), rows, cross)

    body += "\n" + CTA.format(h=esc(topic["cta_h"]), p=esc(topic["cta_p"]),
                              href="../education.html", label="Back to education")
    body += "\n</main>\n\n" + FOOTER + TAIL
    return body


def main():
    total = 0
    for name in ORDER:
        data = json.load(io.open(os.path.join(TOPICS, name + ".json"), encoding="utf-8"))
        topic, arts = data["topic"], data["articles"]
        lookup = {a["slug"]: a for a in arts}

        out = os.path.join(SITE, topic["dir"])
        if not os.path.isdir(out):
            os.makedirs(out)

        io.open(os.path.join(out, "index.html"), "w", encoding="utf-8",
                newline="\n").write(wrap_arrows(render_hub(topic, arts)))
        for a in arts:
            html = render_article(a, topic, lookup)
            io.open(os.path.join(out, a["slug"] + ".html"), "w", encoding="utf-8",
                    newline="\n").write(wrap_arrows(html))

        total += len(arts)
        print("  %-10s %d articles -> site/%s/" % (topic["dir"], len(arts), topic["dir"]))

    print("wrote %d hub pages and %d articles" % (len(ORDER), total))


if __name__ == "__main__":
    main()
